(setf books '((the-dispossesed ursula-leguine)
              (catch-22 joseph-heller)
              (cats-cradle kurt-vonnegut)
              (snow-crash neil-stephenson)
              (the-magicians lev-grossman)))